--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HiroshimaTeam/AntiNoArmorPlayerArea-HiroTeam
build-by-default: true
branches:
- master
projects:
  AntiNoArmorPlayerArea-HiroTeam:
    path: ""
...
